### [CVE-2025-61912](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-61912)
![](https://img.shields.io/static/v1?label=Product&message=python-ldap&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=%3C%203.4.5%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-116%3A%20Improper%20Encoding%20or%20Escaping%20of%20Output&color=brightgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-170%3A%20Improper%20Null%20Termination&color=brightgreen)

### Description

python-ldap is a lightweight directory access protocol (LDAP) client API for Python. In versions prior to 3.4.5, ldap.dn.escape_dn_chars() escapes \x00 incorrectly by emitting a backslash followed by a literal NUL byte instead of the RFC-4514 hex form \00. Any application that uses this helper to construct DNs from untrusted input can be made to consistently fail before a request is sent to the LDAP server (e.g., AD), resulting in a client-side denial of service. Version 3.4.5 contains a patch for the issue.

### POC

#### Reference
- https://github.com/python-ldap/python-ldap/security/advisories/GHSA-p34h-wq7j-h5v6

#### Github
No PoCs found on GitHub currently.

